[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[lint]
exclude_lints = ["unaliased-plain-import"]

[rpc_endpoints]
arbitrum="https://arb1.arbitrum.io/rpc"
ethereum="https://eth.llamarpc.com"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
